// <auto-generated />
using ControleCustos.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ControleCustos.Api.Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180425034833_ControleCustosDB")]
    partial class ControleCustosDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ControleCustosDB")
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleCustos.Api.Database.Entity.DepartamentoEntity", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Codigo");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(100);

                    b.HasKey("Codigo")
                        .HasName("CodigoDepartamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("ControleCustos.Api.Database.Entity.FuncionarioEntity", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Codigo");

                    b.Property<int?>("DepartamentoCodigo");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(200);

                    b.HasKey("Codigo")
                        .HasName("CodigoFuncionario");

                    b.HasIndex("DepartamentoCodigo");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ControleCustos.Api.Database.Entity.MovimentacaoEntity", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Codigo");

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(500);

                    b.Property<int?>("FuncionarioCodigo");

                    b.Property<decimal>("Valor")
                        .HasColumnName("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo")
                        .HasName("CodigoMovimentacao");

                    b.HasIndex("FuncionarioCodigo");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("ControleCustos.Api.Database.Entity.FuncionarioEntity", b =>
                {
                    b.HasOne("ControleCustos.Api.Database.Entity.DepartamentoEntity", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoCodigo");
                });

            modelBuilder.Entity("ControleCustos.Api.Database.Entity.MovimentacaoEntity", b =>
                {
                    b.HasOne("ControleCustos.Api.Database.Entity.FuncionarioEntity", "Funcionario")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("FuncionarioCodigo");
                });
#pragma warning restore 612, 618
        }
    }
}
